<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Substituciones</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Profesor: M.en.C. Miguel Angel Pérez León</i></h5>
    <h5 align="center"><i>Ayudante: Jesús Iván Coss Calderón</i></h5>
    <h5 align="center"><i>Materia: Análisis numérico</i></h5>
  </font>

**Objetivo general**

* Aprender los fundamentos de los algoritmos de sustitución.

**Objetivos particulares**

* Conocer el algoritmo de sustitución hacia delante.
* Conocer el algoritmo de sustitución hacia atrás.

<a name='c1'></a>

## Contenido

- [Introducción](#1)
- [Substituciones (hacia adelante, hacia atrás)](#2)
    - [Substitución hacia adelante](#2-1)
    - [Ejemplo](#2-2)
    - [Substitución hacia atrás](#2-3)
    - [Ejemplo](#2-4)
    - [Ejemplo con un sistema de ecuaciones](#2-5)
- [Resumen](#3)
- [Referencias](#4)

<a name='1'></a>

# Introducción

[regresar al contenido](#c1) 

Gran parte de las factorizaciones empleadas para evitar el cálculo de la matriz inversa (si no es que todas) hacen uso de la substitución hacia adelante y substitución hacia atrás.

Es por eso que realizar un análisis detallado del mismo es muy buena idea, antes de continuar.

<a name='2'></a>

# Substituciones (hacia adelante, hacia atrás)

[regresar al contenido](#c1) 


Una vez que ya se tiene una matriz triangular (superior o inferior) es muy sencillo resolver un sistema de ecuaciones empleando alguna de estas substituciones.

La idea general es que dado un sistema del tipo $A\vec{x}=\vec{b}$, la matriz $A\in M_{n\times n}$ puede ser factorizada empleando alguno de los métodos previamente mencionados *(LU, QR, Cholesky)* y una vez que se tenga alguna de estas factorizaciones es posible emplear algun tipo de subtitución para resolver el sistema original.

<a name='2-1'></a>

# Substitución hacia adelante

[regresar al contenido](#c1) 

Supongamos que se tiene una matríz triangular inferior $L\in M_{n\times n}$ sobre $\mathbb{R}$ y los correspondientes vectores, $\vec{y},\vec{b}\in\mathbb{R}^{n}$ podemos pensar en resolver el sistema:

$$L\vec{y}=\vec{b}$$

Para resolver dicho sistema empleamos el siguiente algoritmo de substitución:

$$y_{i}=\frac{b_{i}-\displaystyle\sum_{j=0}^{i-1}l_{ij}y_{j}}{l_{ii}}\quad i=0,\ldots,(n-1)$$

<a name='2-2'></a>

# Ejemplo

[regresar al contenido](#c1) 

$$\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
-1 & 3 & 1
\end{array}\right)\left(\begin{array}{c}
y_{0}\\
y_{1}\\
y_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
6\\
1
\end{array}\right)$$

Encontrar la primera entada del vector $\vec{y}$ es trivial

$$y_{0}=5$$

La siguiente entrada involucra a $y_{0}$, es decir:

$$y_{1}=\frac{6-\left(\left(-2\right)\left(y_{0}\right)\right)}{l_{11}}=\frac{6-\left(\left(-2\right)\left(5\right)\right)}{1}=16$$

Finalmente, la última entrada de $\vec{y}$ se calcula empleando $y_{1}$ y $y_{0}$:

$$y_{2}=\frac{1-\left(\left(-1\right)\left(y_{0}\right)+\left(3\right)\left(y_{1}\right)\right)}{l_{22}}=\frac{1-\left(\left(-1\right)\left(5\right)+\left(3\right)\left(16\right)\right)}{1}=-42$$

Empleando **substitución hacia adelante** se tiene que:

$$\vec{y}=\left(\begin{array}{c}
5\\
16\\
-42
\end{array}\right)$$

<a name='2-3'></a>

# Substitución hacia atrás 

[regresar al contenido](#c1) 

Supongamos que se tiene una matríz triangular superior $U \in M_{n\times n}$ sobre $\mathbb{R}$ y los correspondientes vectores, $\vec{x},\vec{y}\in\mathbb{R}^{n}$ podemos pensar en resolver el sistema. 

$$U\vec{x}=\vec{y}$$

Para resolver dicho sistema empleamos el siguiente algoritmo de substitución.

$$x_{i}=\frac{y_{i}-\displaystyle\sum_{j=i+1}^{n-1}u_{ij}x_{j}}{u_{ii}}\quad i=(n-1),\ldots,0$$

<a name='2-4'></a>

# Ejemplo

[regresar al contenido](#c1) 

$$
\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 0 & 3
\end{array}\right)\left(\begin{array}{c}
x_{0}\\
x_{1}\\
x_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
16\\
-42
\end{array}\right)
$$

Encontrar la última entada del vector $\vec{x}$ es trivial

$$x_{2}=\frac{-42}{u_{22}}=\frac{-42}{3}=-14$$

La siguiente entrada involucra a $x_{2}$, es decir:

$$x_{1}=\frac{16-\left(\left(1\right)\left(x_{2}\right)\right)}{u_{11}}=\frac{16-\left(\left(1\right)\left(-14\right)\right)}{5}=6$$

Finalmente la primer entrada de $x$ se calcula empleando $x_{2}$ y $x_{1}$:

$$x_{0}=\frac{5-\left(\left(1\right)\left(x_{2}\right)+\left(-3\right)\left(x_{1}\right)\right)}{u_{00}}=\frac{5-\left(\left(1\right)\left(-14\right)+\left(-3\right)\left(6\right)\right)}{-4}=-9.25$$

Por último, mediante **substitución hacia atras** se tiene que:

$$\vec{x}=\left(\begin{array}{c}
-9.25\\
6\\
-14
\end{array}\right)$$

En python ambos algoritmos lucen así:

In [4]:
import numpy as np

# algoritmo para sustitucion hacia delante
# n es el tamano de la dimension del problema
# matriz L, vector b ya estan dados como parametros
# guardar los resultados en el vector y
# Ly=b
def sustDelante(L, b):
    n=len(L)
    y=np.empty_like(b)
    y[0] = b[0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(0,i):
            y[i] -= L[i][j]*y[j]
    return y

# algoritmo para sustitucion hacia atras
# n es el tamano de la dimension del problema
# matriz U, vector y ya estan dados como parametros
# guardar los resultados en el vector x
# Ux=y
def sustAtras(U, y):
    n=len(U)
    x=np.empty_like(y)
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] -= U[i][j]*x[j]
        x[i] /= U[i][i]
    return x


<a name='2-5'></a>

# Ejemplo con un sistema de ecuaciones

Supongamos que tenemos el sistema $A\vec{x}=\vec{b}$.

[regresar al contenido](#c1) 


$$\left(\begin{array}{ccc}
-4 & -3 & 1\\
8 & 11 & -1\\
4 & 18 & 5
\end{array}\right)\left(\begin{array}{c}
x_{0}\\
x_{1}\\
x_{2}
\end{array}\right)=\left(\begin{array}{c}
5\\
6\\
1
\end{array}\right)$$

Y su respectiva factorización $A=LU$.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 0 & 3
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
-1 &{3} & 1
\end{array}\right)$$

In [5]:
U = np.array([[-4,-3,1],[0,5,1],[0,0,3]])
L = np.array([[1,0,0],[-2,1,0],[-1,3,1]])

# Comprobamos que la factorizacion es correcta
print(np.matmul(L,U))

[[-4 -3  1]
 [ 8 11 -1]
 [ 4 18  5]]


Primero encontramos la solución del sistema $L\vec{y}=\vec{b}$ empleando sistitución hacia adelante.

In [6]:
# Se definene los vectores
b = np.array([5.0,6.0,1.0])
# Usamos el algoritmo para encontrar la solucion
y = sustDelante(L, b)

# Se imprime el resultado
print(y)

[  5.  16. -42.]


Ya que se conoce el valor del vector $\vec{y}$ ahora podemos resolver el sistema $U\vec{x}=\vec{y}$

In [7]:
# Usamos el algoritmo para encontrar la solucion
x = sustAtras(U, y)

# Se imprime el resultado
print(x)

[ -9.25   6.   -14.  ]


Por lo tanto la solución al sistema original $A\vec{x}=\vec{b}$, es.

$$\vec{x}=\left(\begin{array}{c}
-9.25\\
6\\
-14
\end{array}\right)$$

<a name='3'></a>

# Resumen

[regresar al contenido](#c1) 



Ya que se tienen una factorización, digamos $\left(LU\right)$ ambas matrices  podemos substituirlas en el sistema original, de tal manera que ahora el sistema luce así.

$$A\vec{x}=LU\vec{x}=\vec{b}$$

Posteriormente podemos replantear la solución del sistema de la siguiente forma.

$$LU\vec{x}=\vec{b}\Longrightarrow L^{-1}LU\vec{x}=L^{-1}\vec{b}\Longrightarrow U\vec{x}=L^{-1}\vec{b}\tag{1}$$

De manera tal, que ahora nos interesa primero encontrar una solución al sistema $L^{-1}\vec{b}=\vec{y}$, mismo que podemos reescribir.

$$L^{-1}\vec{b}=\vec{y}\Longrightarrow LL^{-1}\vec{b}=L\vec{y}\Longrightarrow\vec{b}=L\vec{y}\Longrightarrow L\vec{y}=\vec{b}\tag{2}$$

La ecuación (2) tiene la ventaja de ser un sistema triangular inferior, es por eso que la solución $\vec{y}$ puede ser calculada fácilmente empleando **substitución hacia adelante**. Y una vez calculada, podemos proceder a resolver el segundo sistema empleando **substitución hacia atrás**.

$$U\vec{x}=\vec{y}\tag{3}$$

Los algoritmos de substitución hacia atrás y hacia adelante son de los algoritmos más elementales para resolver un sistema de ecuaciones, sin embargo vale la pena notar algunas cosas.

*   ¿Por que es buena idea emplear estos algoritmos en lugar de buscar la inversa de la matriz $A$?.
*   En términos de elementales (+, -, *, /), ¿cuántas operaciones se realizan al emplear el algoritmo de sustitución hacia adelante?.
*   En términos de operaciones (+, -, *, /), ¿cuántas operaciones se realizan al emplear el algoritmo de sustitución hacia atras?.
*   En total, ¿cuántas operaciones se realizan cuando se resuelve un sistema $LU\vec{x}=\vec{b}$ empleando sustitución hacia adelante y despues hacia atrás?.


<a name='4'></a>

# Referencias

[regresar al contenido](#c1) 

* Justin Solomon: Numerical Algorithms.

* Jaan Kiusalaas: Numerical Methods in Engineering with Python.

* Richard L. Burden, J. Douglas Faires: Análisis Numérico, Math Learning.

* Riswan Butt: Numerical Analysys Using Matlab, Jones and Bartlett.

* Ward Cheney, David Kincaid: Métodos Numéricos y Computación, Cenage Learning.